version: '3'
services:
  frontend:
    build:
      context: ./client
    ports:
      - "4200:4200"

  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase


