version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: matricula
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - networkEscola
networks:
  networkEscola:
    driver: bridge

